//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiudadTatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public string Tatuador { get; set; }
        public string Opinion { get; set; }
        public int Estrellas { get; set; }
    }
}
