//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiudadTatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tatuaje
    {
        public int id { get; set; }
        public string Descripcion { get; set; }
        public string categoria { get; set; }
        public byte[] imagen { get; set; }
        public string fecha { get; set; }
        public string etiqueta { get; set; }
    }
}
